feeds/urls.py
from django.conf.urls import patterns
from django.conf.urls import *
from django.template.defaultfilters import slugify

from . import views

urlpatterns = patterns('',
        url(r'^feed/subscribe', views.FeedSubscribeView.as_view(),
            name='feed_subscribe',),
        url(r'^list/create', views.ListCreateView.as_view(),
            name='list_create',),
        url(r'^list/update/(?P<pk>\d+)/$', views.ListUpdateView.as_view(),
            name='list_update',),
        url(r'^list/delete/(?P<pk>\d+)/$', views.ListDeleteView.as_view(),
            name='list_delete',),
        url(r'^like_article/(?P<article_id>\d+)/$', views.ArticleLikeView.as_view(),
            name='like_article',),
        url(r'^saved-articles/$', views.SavedArticlesView.as_view(), 
            name='saved_articles'),
        url(r'^(?P<pk>\d+)/$', views.ArticleDetailView.as_view(),
            name='article_detail',),
        url(r'^$', views.ArticleListView.as_view(),
            {'filter':'all'},
            name='article_list',),
        url(r'^feed/(?P<feed_id>\d+)/$', views.ArticleListView.as_view(),
            {'filter':'feed'},
            name='feed_view'),
        url(r'^list/(?P<list_id>\d+)/$', views.ArticleListView.as_view(),
            {'filter':'list'},
            name='list_detail',),
)

feeds/models.py
from django.db import models
from django.conf import settings
from dynamic_scraper.models import Scraper, SchedulerRuntime
from scrapy.contrib.djangoitem import DjangoItem
from django.dispatch import receiver
from taggit.managers import TaggableManager
from django.template.defaultfilters import slugify

class Feed(models.Model):
    name = models.CharField(max_length=200)
    url = models.URLField()
    icon = models.URLField(blank=True, null=True)
    description = models.TextField(blank=True)
    scraper = models.ForeignKey(Scraper, blank=True, null=True, on_delete=models.SET_NULL)
    scraper_runtime = models.ForeignKey(SchedulerRuntime, blank=True, null=True, on_delete=models.SET_NULL)
    tags = TaggableManager(blank=True)
    slug = models.SlugField()
    category = models.ForeignKey('categories.Category', blank=True, null=True)

    def __unicode__(self):
            return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)

        super(Feed, self).save(*args, **kwargs)


class Article(models.Model):
    class Meta:
        ordering = ['-pubdate']

    title = models.CharField(max_length=300)
    feed = models.ForeignKey(Feed)
    description = models.TextField(blank=True)
    url = models.URLField()
    pubdate = models.DateTimeField()
    author = models.CharField(max_length=200, blank=True)
    checker_runtime = models.ForeignKey(SchedulerRuntime, blank=True, null=True, on_delete=models.SET_NULL)
    tags = TaggableManager()
    slug = models.SlugField(max_length=200)

    def __unicode__(self):
            return self.title
                
    def save(self, *args, **kwargs):
        if not self.id:
            trimmed_title = ' '.join(self.title.split()[:5])
            self.slug = slugify(trimmed_title)
            
        super(Article, self).save(*args, **kwargs)


class ArticleItem(DjangoItem):
    django_model = Article

class List(models.Model):
    name = models.CharField(max_length=200)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL)
    feeds = models.ManyToManyField(Feed)
    category = models.ForeignKey('categories.Category', blank=True, null=True)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return "/reader/list/%i" % self.id

@receiver(models.signals.pre_delete)
def pre_delete_handler(sender, instance, using, **kwargs):
    if isinstance(instance, Article):
      if instance.checker_runtime:
        instance.checker_runtime.delete()

models.signals.pre_delete.connect(pre_delete_handler)

templates/base-before-ember.html
{% load staticfiles %}<!DOCTYPE html>
<html>
    <head>
        <title>Viligr</title>
        <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'css/viligr.css' %}" rel="stylesheet" type="text/css" />
<script src="{% static 'js/jquery.js' %}" type="text/javascript"></script>
<script src="{% static 'js/handlebars.js' %}" type="text/javascript"></script>
<script src="{% static 'js/ember.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/ember-data.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/ember-data-django-rest-adapter.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/jquery.cookie.js' %}"></script>
    </head>
    <body>
        {% block navbar %}
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Viligr</a>
      <div class="btn-group pull-right">
          {% if user.is_authenticated %}
        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="icon-user"></i> {{ user.first_name }}
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{% url "profile" %}">Profile</a></li>
          <li class="divider"></li>
          <li><a href="{% url "my_logout" %}">Sign Out</a></li>
      </ul>
      {% else %}
      <a class="btn" href="{% url "login" %}">
          <i class="icon-user"></i> Login
          <span class="caret"></span>
        </a>
        
      {% endif %}
      </div>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
        
<form class="navbar-search pull-left">
  <input type="text" class="search-query" placeholder="Search">
</form>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>
{% endblock navbar %}
<div class="main">
    <div class="box">
        <div class="row-fluid">
            {% block leftcolumn %}
            <div class="column span2">
              <ul class="nav nav-list nav-fixed-sidebar">
              <li class="divider"></li>
              <li class="active"><a href="{% url "article_list" %}">Home</a></li>
                <li class="divider"></li>
                <li>
                    <a href="/reader/">Know</a>
                    <ul class="nav nav-list">
                        <li><a href="{% url "list_create" %}" class="new-list">+ New List</a></li>
                        {% for list in user_lists %}
                        <li><a href="{% url 'list_detail' list.id %}">{{ list.name }}</a></li>
                        {% endfor %}
                        <li><a href="{% url "feed_subscribe" %}">+ Add Content</a></li>
                    </ul>
                </li>
                <li class="divider"></li>
                <li><a href="#">Do</a></li>
                <li class="divider"></li>
                <li><a href="#">Get</a></li>
                <li class="divider"></li>
                <li><a href="{% url "saved_articles" %}">Saved</a></li>
                <li class="divider"></li>
                <li><a href="#">Social</a></li>
                <li class="divider"></li>
                <a href="#" class="btn btn-danger">Publish</a>
                <li class="divider"></li>
              </ul>
          </div>
          {% endblock leftcolumn %}
            <div class="column span7">
          {% block messages %}
                {% if messages %}
                    <ul class="messages unstyled">
                        {% for message in messages %}
                        <li id="message_{{ forloop.counter }}"
                                {% if message.tags %} class="{{ message.tags }} label label-success"
                                    {% endif %}>
                               {{ message }}
                        </li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endblock messages %}
{% block content %}

{% endblock content %}
            </div>

            {% block rightcolumn %}
        <div class="column span3">
            <div id="twitter-feed">
            <h2>Twitter Feed</h2>
                <a class="twitter-timeline" height="570px" href="https://twitter.com/ViligrNYC" data-widget-id="349715214213709824">Tweets by @ViligrNYC</a>
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

            </div>
            <div class="tabbable">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#tab1" data-toggle="tab">Most Read</a></li>
                    <li><a href="#tab2" data-toggle="tab">Favorites</a></li>
                    <li><a href="#tab3" data-toggle="tab">Shared</a></li>
                </ul>
            </div>
        </div>
        {% endblock rightcolumn %}
        </div>
      
    </div>
</div>
<script type="text/javascript">

$(document).ready(function () {

    $('.new-list').click(function() {
        var url = $(this).attr('href');
        
    });

});
  App.Store = DS.DjangoRESTStore.extend({
          adapter: DS.DjangoRESTAdapter.create()
        });
</script>

</body>
</html>

templates/base.html
{% load staticfiles %}
{% load dajaxice_templatetags %}
<!DOCTYPE html>
<html>
    <head>
        <title>Viligr</title>
        <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'css/viligr.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'css/feed_list_style.css' %}" rel="stylesheet" type="text/css" />
        <link href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" type="text/css" />
    </head>
    <body>
        {% block navbar %}
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Viligr</a>
      <div class="btn-group pull-right">
          {% if user.is_authenticated %}
        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="icon-user"></i> {{ user.first_name }}
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{% url "profile" %}">Profile</a></li>
          <li class="divider"></li>
          <li><a href="{% url "my_logout" %}">Sign Out</a></li>
      </ul>
      {% else %}
      <a class="btn" href="{% url "login" %}">
          <i class="icon-user"></i> Login
          <span class="caret"></span>
        </a>
        
      {% endif %}
      </div>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
        
    <!--
  <input type="text" class="search-query" placeholder="Search">
-->
<form method="get" action="/search/" class="navbar-search pull-left" id="header-search-form">
{{ search_form }}
    <input type="submit" value="Search" class="btn submit">
</form>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>
{% endblock navbar %}
<div class="main">
    <div class="box">
        <div class="row-fluid">
            {% block leftcolumn %}
            <div class="column span2">
              <ul class="nav nav-list nav-fixed-sidebar">
              <li class="divider"></li>
              <li class="active"><a href="{% url "article_list" %}">Home</a></li>
                <li class="divider"></li>
                <li>
                    <a href="/reader/">Know</a>
                </li>
                <li class="divider"></li>
                    <ul class="nav nav-list">
                        <li><a href="javascript:void(0)" id="new-list">+ New List</a></li>
                        {% for list in user_lists %}
                        <li><a href="{% url 'list_detail' list.id %}">{{ list.name }}</a></li>
                        {% endfor %}
                        <li><a href="{% url "feed_subscribe" %}">+ Add Content</a></li>
                    </ul>
                <li class="divider"></li>
                <li><a href="{% url "saved_articles" %}">Saved</a></li>
                <li class="divider"></li>
              </ul>
          </div>
          {% endblock leftcolumn %}
            <div class="column span7">
          {% block messages %}
                {% if messages %}
                    <ul class="messages unstyled">
                        {% for message in messages %}
                        <li id="message_{{ forloop.counter }}"
                                {% if message.tags %} class="{{ message.tags }} label label-success"
                                    {% endif %}>
                               {{ message }}
                        </li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endblock messages %}
{% block content %}

{% endblock content %}
           </div>
<div id="add-list" class="trigger right" style="display:none;position:absolute;right:0;top:100;">

</div>

            {% block rightcolumn %}
        <div class="column span3">
            <div id="twitter-feed">
            <h2>Twitter Feed</h2>
                <a class="twitter-timeline" height="570px" href="https://twitter.com/ViligrNYC" data-widget-id="349715214213709824">Tweets by @ViligrNYC</a>
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

            </div>
            <div class="tabbable">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#tab1" data-toggle="tab">Most Read</a></li>
                    <li><a href="#tab2" data-toggle="tab">Favorites</a></li>
                    <li><a href="#tab3" data-toggle="tab">Shared</a></li>
                </ul>
            </div>
        </div>
        {% endblock rightcolumn %}
        </div>
      
    </div>
</div>
<script src="{% static 'js/jquery.js' %}" type="text/javascript"></script>
<script src="{% static 'js/vendor/jquery.cookie.js' %}" type="text/javascript"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static '/static/js/vendor/jquery.ba-serializeobject.min.js' %}"></script>
<script src="{% static '/static/dajax/jquery.dajax.core.js' %}"></script>
{% dajaxice_js_import %}
<script type="text/javascript">
    Dajaxice.feeds.say_hello(Dajax.process);
</script>
<script type="text/javascript">
$(document).ready(function(){
function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    crossDomain: false, // obviates need for sameOrigin test
    beforeSend: function(xhr, settings) {
        var csrftoken = $.cookie('csrftoken');
        if (!csrfSafeMethod(settings.type)) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});
});
</script>
<script src='http://connect.facebook.net/en_US/all.js'></script>
<script src="{% static 'js/feed_list.js' %}"></script>
<script src="{% static 'js/actions.js' %}"></script>
<script type="text/javascript"> 

      FB.init({appId: "135472653328186", status: true, cookie: true});

      function postToFeed(link) {
        
        var url = $(link).attr('data-url');
        var title = $(link).closest('.article').find('.title').html();
        var domain = url_domain(url);
        var description = $(link).closest('.article')
                        .find('.description').html()  
                        .trim().substring(0, 300)
                        .split(" ").slice(0, -1).join(" ") + "...";
                          
        console.log(url + ' ' + title);
        // calling the API ...
        var obj = {
          method: 'feed',
          link: url,
          name: title,
          caption: domain,
          description: description
        };

        function callback(response) {
          document.getElementById('msg').innerHTML = "Post ID: " + response['post_id'];
        }

        FB.ui(obj, callback);
      }

function url_domain(data) {
  var    a      = document.createElement('a');
         a.href = data;
  return a.hostname;
}
    </script>
<script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
<script type="text/javascript">
$(document).ready(function() {
$('#new-list').click(function(){
    $('#add-list').load('/reader/list/create/', function(response,status,xhr){
        if(status != 'success'){
            console.log('nooooo');
        } else {
            if(!this.is(':visible')){ 
                $(this).toggle();
            }
        }
    });
});
            });
        </script>
</body>
</html>

templates/index.html
{% load staticfiles %}
{% load compress %}
<html>
    <body>
    <div id="articles">
        
    </div>
<script src="{% static 'js/vendor/jquery.js' %}" type="text/javascript"></script>
<script type="text/javascript">
  jQuery(document).ajaxSend(function(event, xhr, settings) {
    if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
      var token = $('meta[name="csrf-token"]').attr('content');
      xhr.setRequestHeader("X-CSRFToken", token);
    }
  });
</script>
{% compress js %}
<script src="{% static 'js/vendor/handlebars-1.0.0-rc.4.js' %}" type="text/javascript"></script>
<script src="{% static 'js/vendor/ember-1.0.0-rc.6.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/vendor/ember-data-0.13.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/vendor/adapter.js' %}" type="text/javascript"></script>
<script src="{% static 'js/app/viligr.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/app/templates/articles.handlebars' %}" type="text/x-handlebars"></script>
<script src="{% static 'js/app/templates/application.handlebars' %}" type="text/x-handlebars"></script>
{% endcompress %}
</body>
</html>

templates/login.html
{% extends "base.html" %}

{% block content %}
{% block login %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
{% endblock login %}
                <a href="{% url "userprofile_create" %}">Create Account</a>
                <a href="{% url "socialauth_begin" "facebook" %}">Login with Facebook</a>
                <a href="{% url "socialauth_begin" "twitter" %}">Login with Twitter</a>
{% endblock content %}

templates/old.base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Viligr</title>

        <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js" type="text/javascript"></script>
    </head>
    <body>
        <header>
            <h1 id="logo">Viligr</h1>
            <menu>
                {% if user.is_authenticated %}
                <li><a href="{% url "my_logout" %}">Logout</a></li>
                <li><a href="/account">Account</a></li>
                <li><a href="/account/update">Update</a></li>
                <li><a href="{% url "article_list" %}">Articles</a></li>
                {% else %}
                <li><a href="{% url "my_login" %}">Login</a></li>
                <li><a href="{% url "socialauth_begin" "facebook" %}">Login with Facebook</a></li>
                <li><a href="{% url "socialauth_begin" "twitter" %}">Login with Twitter</a></li>
                <li><a href="/account/create">Create Account</a></li>
                {% endif %}
            </menu>
        </header>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li id="message_{{ forloop.counter }}"
                {% if message.tags %} class="{{ message.tags }}"
                    {% endif %}>
               {{ message }}
        </li>
        {% endfor %}
    </ul>
{% endif %}
{% block content %}

{% endblock %}
    </body>
</html>